# Generated by Django 3.1.1 on 2021-01-30 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='blog.category', verbose_name='پدر')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('confirm', models.BooleanField(default=False, verbose_name='تایید')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': [('wirte', 'نوشتن'), ('edit', 'ویرایش'), ('comment', 'نظر'), ('confirm', 'تایید'), ('active', 'فعال')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('confirm', models.BooleanField(default=False, verbose_name='تایید')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='', verbose_name='عکس پست')),
            ],
            options={
                'permissions': [('wirte', 'نوشتن'), ('edit', 'ویرایش'), ('comment', 'نظر'), ('confirm', 'تایید'), ('active', 'فعال')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='پرجسب')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن')),
                ('photo', models.ImageField(upload_to='', verbose_name='عکس کاربر')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='آیدی کاربری')),
            ],
        ),
        migrations.CreateModel(
            name='Post_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='blog.post', verbose_name='پست')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.tags', verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='Post_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.comments', verbose_name='نظر')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='پست')),
            ],
        ),
        migrations.CreateModel(
            name='Post_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category', verbose_name='دسته بندی')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_cat', to='blog.post', verbose_name='پست')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='blog.Post_category', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(through='blog.Post_comments', to='blog.Comments'),
        ),
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(related_name='user_dislike_post', related_query_name='user_dislike_post', to='blog.User_info'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='user_like_post', related_query_name='user_like_post', to='blog.User_info'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='blog.Post_tags', to='blog.Tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_post', to='blog.user_info', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='comments',
            name='dislike',
            field=models.ManyToManyField(related_name='user_dislike_comments', related_query_name='user_dislike_comments', to='blog.User_info'),
        ),
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(related_name='user_like_comments', related_query_name='user_like_comments', to='blog.User_info'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to='blog.user_info', verbose_name='کاربر'),
        ),
    ]
