# Generated by Django 3.1.1 on 2021-02-03 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='blog.category', verbose_name='پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', tinymce.models.HTMLField(verbose_name='متن')),
                ('confirm', models.BooleanField(default=False, verbose_name='تایید')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='user_dislike_comments', related_query_name='user_dislike_comments', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='user_like_comments', related_query_name='user_like_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'permissions': [('wirte', 'نوشتن'), ('edit', 'ویرایش'), ('comment', 'نظر'), ('confirm', 'تایید'), ('active', 'فعال')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='پرجسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن')),
                ('photo', models.ImageField(upload_to='uploads/user_photo', verbose_name='عکس کاربر')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='آیدی کاربری')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', tinymce.models.HTMLField(verbose_name='متن')),
                ('confirm', models.BooleanField(default=False, verbose_name='تایید')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='uploads/post_image', verbose_name='عکس پست')),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('comments', models.ManyToManyField(to='blog.Comments')),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='user_dislike_post', related_query_name='user_dislike_post', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='user_like_post', related_query_name='user_like_post', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='blog.Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_post', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'permissions': [('wirte', 'نوشتن'), ('edit', 'ویرایش'), ('comment', 'نظر'), ('confirm', 'تایید'), ('active', 'فعال')],
                'abstract': False,
            },
        ),
    ]
