# Generated by Django 3.1.1 on 2021-01-27 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
