# Generated by Django 3.1.1 on 2021-01-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210130_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'permissions': [('wirte', 'نوشتن'), ('edit', 'ویرایش'), ('comment', 'نظر'), ('confirm', 'تایید'), ('active', 'فعال')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('wirte', 'نوشتن'), ('edit', 'ویرایش'), ('comment', 'نظر'), ('confirm', 'تایید'), ('active', 'فعال')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
    ]
