# Generated by Django 3.1.1 on 2021-01-30 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='عکس کاربر')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='آیدی کاربری')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='blog.comments', verbose_name='like نظر'),
        ),
        migrations.AlterField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.user_info', verbose_name='صاحب نظر'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_info', verbose_name='صاحب علاقه مندی'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.user_info', verbose_name='نویسنده'),
        ),
    ]
