# Generated by Django 3.1.1 on 2021-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210206_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
