# Generated by Django 3.1.1 on 2021-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210130_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن'),
        ),
    ]
