# Generated by Django 3.1.1 on 2021-01-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_info_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'permissions': [('confirm', 'تایید کردن نظر')]},
        ),
    ]
