# Generated by Django 3.1.1 on 2021-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210208_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=100, null=True, verbose_name='fontawesome'),
        ),
    ]
