# Generated by Django 3.1.1 on 2021-02-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210209_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'permissions': [('confirm_%(class)s', 'تایید کردن'), ('active_%(class)s', 'فعال کردن')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('confirm_%(class)s', 'تایید کردن'), ('active_%(class)s', 'فعال کردن')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
