# Generated by Django 3.1.1 on 2021-02-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210210_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'permissions': [('confirm', 'تایید کردن'), ('active', 'فعال کردن')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('confirm', 'تایید کردن'), ('active', 'فعال کردن')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
