# Generated by Django 3.1.1 on 2021-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210210_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShowPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/slide_show', verbose_name='عکس اسلاید')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
            ],
        ),
    ]
