# Generated by Django 3.1.1 on 2021-02-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_slideshowpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideShowPost',
            new_name='MainContent',
        ),
        migrations.AlterModelOptions(
            name='maincontent',
            options={'verbose_name': 'محتوای اصلی', 'verbose_name_plural': 'محتوای اصلی'},
        ),
    ]
