# Generated by Django 3.1.1 on 2021-02-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210213_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='active',
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
