# Generated by Django 3.1.1 on 2021-02-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210222_0044'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='blog_word_word_50b08a_idx'),
        ),
    ]
