# Generated by Django 3.1.1 on 2021-03-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210222_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tags', verbose_name='برجسب ها'),
        ),
        migrations.AlterField(
            model_name='word',
            name='post',
            field=models.ManyToManyField(null=True, related_name='word', to='blog.Post'),
        ),
    ]
